name: test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # run all tests so we see which gem/ruby combinations break
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1', head, jruby-head]
        os: [ubuntu-latest, windows-latest]
        gemfile: [cucumber_3, cucumber_4, cuke_modeler_3_minimum, cuke_modeler_3]
        task: [spec]
        include:
          - ruby: '2.5' # lowest supported version
            os: ubuntu-latest
            gemfile: cuke_modeler_3 # Any one of the gemfiles should be fine
            task: rubocop
        exclude:
          # CukeModeler 3.x does not support Ruby 3 until CM 3.6
          - gemfile: cuke_modeler_3_minimum
            ruby: jruby-head
          - gemfile: cuke_modeler_3_minimum
            ruby: head
          - gemfile: cuke_modeler_3_minimum
            ruby: '3.1'
          - gemfile: cuke_modeler_3_minimum
            ruby: '3.0'
    env: # $BUNDLE_GEMFILE must be set at the job level, so that it is set for all steps
      BUNDLE_GEMFILE: ci_gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: rake ${{ matrix.task }}
      # allow ruby/jruby-head to fail since they are moving targets
      # TODO: this will always show green, fix once https://github.com/actions/toolkit/issues/399 is resolved
      continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
      run: bundle exec rake ${{ matrix.task }}
