name: test

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', '2.7', '2.6', '2.5', head, jruby-head]
        os: [ubuntu-latest, windows-latest]
        task: [default]
        include:
        - ruby: '2.5' # lowest supported version
          os: ubuntu-latest
          task: rubocop
    env:
      RUBYOPT: -W0
      # avoid warnings from https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@master
    - name: Setup OS dependencies
      uses: MSP-Greg/setup-ruby-pkgs@v1
      with:
        bundler: 2.2.15
        ruby-version: ${{ matrix.ruby }}
        apt-get:  libsqlite3-dev
    - name: Install dependencies
      run: bundle install --jobs 4
    - name: rake ${{ matrix.task }}
      run: bundle exec rake ${{ matrix.task }}
      # allow ruby/jruby-head to fail since they are moving targets
      # TODO: this will always show green, fix once https://github.com/actions/toolkit/issues/399 is resolved
      continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
